version: '3.4'

services:
  chatapplication:
    depends_on:
      - rabbitmq
      - sqlserver
    image: olandese/chatapplication
    container_name: chat
    environment:
      - CONN=${CONN}
    ports:
      - 5000:80

  rabbitmq:
    image: olandese/rabbit-qs2
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  sqlserver:
    image: microsoft/mssql-server-windows-developer
    container_name: sqlserver
    environment:
      - sa_password=Q1w2e3r4t5y6
      - ACCEPT_EULA=Y
    ports:
      - 1433:1433
