version: '3.4'

services:
  chatapplication:
    depends_on:
      - rabbitmq
    image: olandese/chatapplication
    container_name: chat
    environment:
      - CONN=${CONN}
    ports:
      - 5000:80

  rabbitmq:
    image: olandese/rabbit-qs2
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
